name: Callable Build Distribution Workflow

on: [workflow_call]

jobs:
  distribution:
    name: Build Distribution (${{ matrix.os }} - ${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["22.0"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm install

      - name: Create "dist/" Folder Contents
        run: npm run build

      - name: Create Package
        run: npm pack
