name: Callable Essential Test Workflow

on: [workflow_call]

jobs:
  test:
    name: Essential (${{ matrix.os }}, ${{ matrix.node }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["22.0"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm install

      - name: Scan Vulnerabilities
        run: npm audit --production

      - name: Lint and Format Check
        run: npm run tidy:ci

      - name: Test Unit
        run: npm run test:ci:coverage
